---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Chrome.app
    - "/Applications/Sublime Text.app"
    - /Applications/iTerm.app
    - /Applications/Spotify.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Daniel Cannon
    git_user_email: daniel@danielcannon.co.uk
#  - role: dotfiles
  - role: brew_package
    tap: thoughtbot/formulae
    package_name: gitsh
  - role: brew_package
    package_name: git-extras
  - role: brew_package
    package_name: git-flow
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: go
  - role: brew_package
    package_name: node
  - role: cask_package
    package_name: java

  # gui
  ## utilities
  - role: cask_package
    package_name: alfred
  - role: cask_package
    package_name: bartender
  - role: cask_package
    package_name: bettertouchtool
  - role: cask_package
    package_name: caffeine
  - role: cask_package
    package_name: flux
  - role: cask_package
    package_name: iterm2
  - role: cask_package
    package_name: keyremap4macbook
  - role: cask_package
    package_name: onepassword
  - role: cask_package
    package_name: sizeup
  - role: cask_package
    package_name: sourcetree
  - role: cask_package
    package_name: transmission
  - role: cask_package
    package_name: transmit
  - role: cask_package
    package_name: the-unarchiver
  ## vms
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vagrant
  ## browsers
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: google-chrome
  ## chat
  - role: cask_package
    package_name: skype
  ## text editors
  - role: cask_package
    package_name: sublime-text-3
  ## entertainment
  - role: cask_package
    package_name: vlc
  ## sync
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: google-drive

